name: Hope Dealer
favicon: null
layout_spectrum: 1
typography_spectrum: 0.52472
title: Hope Dealer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#02092b'
    - '#fadaab'
    - '#b2978a'
    - '#65655b'
    - '#872e3c'
  brandStrength: 1
  lightness: 0.6143768629990518
  saturation: 0.359377377666533
  rhythmicContrast: 0.5
purpose: []
