name: Hope Dealer
favicon: null
layout_spectrum: 0.49786
typography_spectrum: 0.4842
title: Hope Dealer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#45565f'
    - '#768b93'
    - '#001720'
    - '#661c1e'
  brandStrength: 0.625
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
