name: Hope Dealer
favicon: null
layout_spectrum: 0.99547
typography_spectrum: 0.4842
title: Hope Dealer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#103744'
    - '#5d0204'
    - '#914133'
    - '#7c9198'
  brandStrength: 0.6875
  lightness: 0.875
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
