name: Hope Dealer
favicon: null
layout_spectrum: 1
typography_spectrum: 0.52472
title: Hope Dealer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#45565f'
    - '#768b93'
    - '#001720'
    - '#661c1e'
  brandStrength: 1
  lightness: 0.6143768629990518
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
